title: PulseGrid Studios Hub
repository: Pulsegridstudios/contributing
theme: minima

url: https://pulsegridstudios.github.io
baseurl: /hub

logo: /assets/images/logo.png

aux_links:
  PulseGrid Studios: https://pulsegridstudios.github.io
  Roblox Game: https://www.roblox.com/games/103236484372211/Looped-Operation
  Wiki: https://pulsegridstudios.github.io/wiki/

plugins:
  - jekyll-relative-links